development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['MSFLOSS_DATABASE_HOST'] %>
  database: <%= ENV['MSFLOSS_DATABASE_NAME'] %>
  username: <%= ENV['MSFLOSS_DATABASE_USER'] %>
  password: <%= ENV['MSFLOSS_DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['MSFLOSS_DATABASE_HOST'] %>
  database: <%= ENV['MSFLOSS_DATABASE_NAME'] %>
  username: <%= ENV['MSFLOSS_DATABASE_USER'] %>
  password: <%= ENV['MSFLOSS_DATABASE_PASSWORD'] %>